# Generated by Django 4.0.4 on 2022-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_ref_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ref',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
