# Generated by Django 4.0.4 on 2022-04-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_ref_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ref',
            old_name='name',
            new_name='gtin',
        ),
    ]
